### ISSUE TITLE
[Bug] Plugin shows wrong amount of episodes in logs

### ISSUE THREAD

**Issue by okan35** [ConfusedPolarBear/intro-skipper#109]
There are 10 episodes in 1 season of one show and jellyfin recognizes this as well but intro skipper plugin shows 156 episodes for the same season of same show. 

Possibly might be because of naming of shows as another one with better naming is working as well.

The show with correct amount of episode info is named as such " ShowName - S01E1 - SomeTitle.mkv" while the one with wrong amount of episode is named as such "ShowName.S01E01.SomeTitle.2160p.WEB-DL.DDP5.1.H-265-Ntb.mkv"

![_20221118_192945.JPG](https://user-images.githubusercontent.com/19223877/202777196-99271435-d9cb-4dae-9770-601181da0cf6.JPG)

Another question is why you make so many requests for images of shows as I believe this would slow things down.

![_20221118_193333.JPG](https://user-images.githubusercontent.com/19223877/202777761-f2ebe0fc-c1fe-47b7-ba35-02aa984d5dd1.JPG)

**Comment by ConfusedPolarBear** [comment]
Please use the [Bug report](https://github.com/ConfusedPolarBear/intro-skipper/issues/new?assignees=&labels=bug&template=bug_report.yml) template when opening a bug report.
