### ISSUE TITLE
Allow Intro Button via Script Injection

### ISSUE THREAD

**Issue by JPVenson** [ConfusedPolarBear/intro-skipper#114]
**Describe the feature you'd like added**
I would like to have a separate script provided via the Plugin e.g "auto-skipper-player-plugin.js" that i could inject via a reverse proxy instead of replacing the whole jellyfin UI.

**Additional context**
This would allow me to use my own modifications while also keeping everything else as pristine as possible.

**Comment by JoshuaMorley** [comment]
I have just had a look at integrating this but it looks like it has already been implemented since November. We are just waiting for the next release: 
https://github.com/ConfusedPolarBear/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs#L79-L79

**Comment by ConfusedPolarBear** [comment]
Closing as this has been implemented in f4e84d4 and will be released in the next version.
