### ISSUE TITLE
Allow autoinjection of ClientSide script

### ISSUE THREAD

**Issue by JPVenson** [ConfusedPolarBear/intro-skipper#117]
**Describe the feature you'd like added**
An optional function that will inject a script tag into the viewer page to allow a one click Implementation without replacing all source files. This can be toggled on/off as an option and will add the script to the viewer.

**Additional context**
The Jellyscrub plugin does exactly this to provide preview images for the video progressbar.
https://github.com/nicknsy/jellyscrub/blob/main/Nick.Plugin.Jellyscrub/JellyscrubPlugin.cs#L38

**Comment by Mavyre** [comment]
I may add that Jellyscrub works on applications (Android, iOS, WebOs...)

**Comment by Mavyre** [comment]
I saw it too. However, didn't had time to test it yet

**Comment by ConfusedPolarBear** [comment]
Closing as this has been implemented in f4e84d4 and will be released in the next version.
