### ISSUE TITLE
jellyfin-ffmpeg now includes libchromaprint

### ISSUE THREAD

**Issue by Shadowghost** [ConfusedPolarBear/intro-skipper#12]
This is just an info that we recently added libchromaprint to jellyfin-ffmpeg.
Once 10.8 stable with jellyfin-ffmpeg 5.0.1-5 gets released you could use ffmpeg to create the fingerprints you're currently generating with fpcalc.

**Comment by ma-karai** [comment]
This would be quite great.

**Comment by ConfusedPolarBear** [comment]
Support for this was added in commit 70b4f0e and will be available in the next release of the plugin.

**Comment by ConfusedPolarBear** [comment]
Closing now that v0.1.5.0 has been released.
