### ISSUE TITLE
Exclude libraries from being intro-skipper

### ISSUE THREAD

**Issue by malikaygar** [ConfusedPolarBear/intro-skipper#120]
**Describe the feature you'd like added**
Being able to exclude different libraries from being added to intro-skipper e.g. anime

**Comment by bruor** [comment]
This is implemented.. https://github.com/ConfusedPolarBear/intro-skipper/issues/37

**Comment by ConfusedPolarBear** [comment]
Duplicate of #37. You can configure the plugin to exclude a library from being analyzed by using the `Limit analysis to the following libraries` setting in the plugin's settings.
