### ISSUE TITLE
Jellyfin 10.8.9: ASS subtitles out of sync after intro skip (subtitle starts over from the begining)

### ISSUE THREAD

**Issue by poulpor** [ConfusedPolarBear/intro-skipper#127]
### Describe the bug

Hi, 
I've just updated to the latest Jellyfin 10.8.9 and noticed this problem I didn't have with Jellyfin 10.8.8. When the intro is skipped, the subtitles are starting over from the beginning of the ASS file.
If I stop after intro skipped then resume, the subtitles are almost in sync again with a 1 second gap (1 second early).

I didn't try to erase introduction timestamps yet.

Thank you very much for this plugin, I don't know if Jellyfin team is planning to integrate it or if you prefer to keep it external, but it has become an essential feature.

### Operating system

DSM (Synology)

### Jellyfin installation method

Docker

### Container image and tag

jellyfin/jellyfin:latest, jellyfin-intro-skipper:latest

### Support Bundle

* Jellyfin version: 10.8.9
* Plugin version: 0.1.7
* Queue contents: 7214 episodes, 441 seasons
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by poulpor** [comment]
A quick update, I apologize, it might not be related to intro-skipper but to jellyfin. I just tried with the new androidTV client 0.15.3, playing the problematic video with ASS subtitle is going fine after intro skipped when using libVLC player. No "restart" of the subtitle just after intro skipped and no out of sync.

**Comment by ConfusedPolarBear** [comment]
Closing as this appears to be an upstream issue.
