### ISSUE TITLE
Update Jellyfin-web to 10.8.9

### ISSUE THREAD

**Issue by JVT038** [ConfusedPolarBear/intro-skipper#128]
The current version is 10.8.5
It would be nice to make use of 10.8.9, as it contains the latest bug fixes and such.

**Comment by Mavyre** [comment]
Tried on 10.8.8 and that works for me :)

**Comment by aleksasiriski** [comment]
> 

I'll make a docker image which uses official latest jellyfin and changes to this webui with intro skipper today, so watch my repos if you want

**Comment by Anirte** [comment]
> > 
> 
> I'll make a docker image which uses official latest jellyfin and changes to this webui with intro skipper today, so watch my repos if you want

Well, if not OP, I will wait, cause official docker image doesn't work for me

**Comment by aleksasiriski** [comment]
> > > 
> > 
> > 
> > I'll make a docker image which uses official latest jellyfin and changes to this webui with intro skipper today, so watch my repos if you want
> 
> Well, if not OP, I will wait, cause official docker image doesn't work for me

I was a bit busy yesterday sry, making it now with and without rffmpeg (I used to have one but deleted it after remaking my docker images)

**Comment by aleksasiriski** [comment]
https://github.com/aleksasiriski/jellyfin-intro-skipper

**Comment by aleksasiriski** [comment]
https://github.com/aleksasiriski/jellyfin-rffmpeg-intro-skipper

**Comment by Mavyre** [comment]
@aleksasiriski Pretty cool. However, that updates the server to 10.8.9 while jellyfin-web stays at the latest commit made by the PolarBear, which is 10.8.5. I think we'd have a little work to merge the 10.8.9 from jellyfin-web to fully update it.

Honestly, I can't wait for a script injection to be made for that plugin 😄

**Comment by aleksasiriski** [comment]
I can try to add building steps of latest jellyfin-web from this repo but that will only make sense if @ConfusedPolarBear updated the web from upstream. If he didn't I don't want to mess with that

**Comment by roib20** [comment]
I see the `confusedpolarbear/jellyfin-intro-skipper` [Dockerfile](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docker/Dockerfile) was updated today to use `jellyfin/jellyfin:10.8.9` as the base image. However on [ghcr.io/confusedpolarbear/jellyfin-intro-skipper](https://ghcr.io/confusedpolarbear/jellyfin-intro-skipper) the `latest` tag is still for 10.8.5 rather than 10.8.9.

**Comment by roib20** [comment]
I made Pull Request #132 to help improve the image functionality and add multi-arch support (AMD64, ARM and ARM64). If anyone wants to help test, the images are available over on my fork: `docker pull ghcr.io/roib20/jellyfin-intro-skipper:10.8.9` or `latest`. Pi testers for the ARM images would be very helpful.

**Comment by roib20** [comment]
> @aleksasiriski Pretty cool. However, that updates the server to 10.8.9 while jellyfin-web stays at the latest commit made by the PolarBear, which is 10.8.5. I think we'd have a little work to merge the 10.8.9 from jellyfin-web to fully update it.
> 
> Honestly, I can't wait for a script injection to be made for that plugin smile

After further checking it appears you are correct. [ConfusedPolarBear](https://github.com/ConfusedPolarBear) /
[jellyfin-web](https://github.com/ConfusedPolarBear/jellyfin-web) is not yet fully updated. This is not to be confused with the server back-end which is updated to v10.8.9.

**Comment by ConfusedPolarBear** [comment]
> The current version is 10.8.5
>
> It would be nice to make use of 10.8.9

Closing, as both the container ([Dockerfile](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docker/Dockerfile), [image](https://github.com/ConfusedPolarBear/intro-skipper/pkgs/container/jellyfin-intro-skipper/67061733?tag=latest)) and the [web interface fork](https://github.com/ConfusedPolarBear/jellyfin-web/tree/intros) have been updated to 10.8.9.
