### ISSUE TITLE
Artifact expired

### ISSUE THREAD

**Issue by seanmcbroom** [ConfusedPolarBear/intro-skipper#129]
### Describe the bug

Pre-compiled web interface download expired

https://github.com/ConfusedPolarBear/intro-skipper/actions/runs/3334786513

### Operating system

Ubuntu

### Jellyfin installation method

Docker

### Support Bundle

* Jellyfin version: 10.8.8
* Plugin version: 0.1.7
* Queue contents: 1815 episodes, 107 seasons
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by frap129** [comment]
You can fork this repo, go to actions, and run the "Publish container" workflow. It will say it failed because you can't publish the container, but you can still download the tar.gz

**Comment by arjunsrinivasan1997** [comment]
I'm getting this issue when I try do to that 
`npm ERR! code EINTEGRITY
npm ERR! sha512-5rjszPzcjFVoDEOarszcbax2WIGT3+fO+W212ZWg9+ylGJgxG1IIcCFjnnBbSdM0lNeIfmMGhhEGovIlr+1yBg== integrity checksum failed when using sha512: wanted sha512-5rjszPzcjFVoDEOarszcbax2WIGT3+fO+W212ZWg9+ylGJgxG1IIcCFjnnBbSdM0lNeIfmMGhhEGovIlr+1yBg== but got sha512-3IUEYIqixzRaxCR15LbcifCbHb0LJFWyULC9C54dnDvCwF39b9MzRnWaIMLK5/gtqpzK1r7Wx+mmNAJur5M0iA==. (6317 bytes)`

**Comment by Svenum** [comment]
@frap129 Does not work for m.

**Comment by arjunsrinivasan1997** [comment]
@Svenum didn't work for me either but I found a copy from another fork. [Here](https://www.dropbox.com/s/4lbjgirkfy4hdyn/jellyfin-web-10.8.0%2B3c3506d946.tar.gz.zip?dl=0) is a link.

**Comment by Svenum** [comment]
Thx
