### ISSUE TITLE
Show Skip intro as long as the intro is playing

### ISSUE THREAD

**Issue by Mavyre** [ConfusedPolarBear/intro-skipper#131]
**Describe the feature you'd like added**
That would be great to have a settings to have the intro button stay as long as the intro is playing, instead of a fixed amount of time. 

**Additional context**
We can do it manually by replacing HideSkipPromptAt by IntroEnd in the code. Having a setting would make it easier to modify

**Comment by 0TTA** [comment]
It might be a good idea to show the Skip Intro for the first 5 seconds and then hide it unless you move the mouse.
