### ISSUE TITLE
Support for Mixed Libraries (TV Shows and Movies)

### ISSUE THREAD

**Issue by iliasalk** [ConfusedPolarBear/intro-skipper#135]
After an initial testing of the plugin it seems that intros are successfully being scanned and skipped only for "TV Shows" type libraries. However I am using as well the mixed library type that contains mostly shows but also some movies. This type of library seems to be ignored completely by the pluggin. Is there a way to include it?

**Comment by ConfusedPolarBear** [comment]
> Is there a way to include it?

Not with the current version of the plugin (v0.1.7), as it does not analyze mixed libraries. Support for mixed libraries was added in bcb5e5e, which will be released in the next version.
