### ISSUE TITLE
Updated to 0.0.3 but auto skip is still missing in the plugin settings

### ISSUE THREAD

**Issue by Joeharrison94** [ConfusedPolarBear/intro-skipper#14]
As the title says I have updated and restarted and also uninstalled and installed again but there is no option in the plugin settings to auto skip?

Any help would be appreciated.

Thanks

**Comment by ConfusedPolarBear** [comment]
Auto skip was added in commit 4ca0511 but wasn't included in a release of the plugin until version 0.1.0.

**Comment by Joeharrison94** [comment]
perfect thanks
