### ISSUE TITLE
I can't  detect intros

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [ConfusedPolarBear/intro-skipper#140]
### Describe the bug

For some reason icant make it start and detext intros and when i do it manually it always resets to 0 after i save and the skip does not appear when playing the show.

### Operating system

Windows 11, DSM 7 on Synology Nas

### Jellyfin installation method

The DSM

### Container image and tag

Jellyfin

### Support Bundle

* Jellyfin version: 10.8.9
* Plugin version: 0.1.7
* Queue contents: 8432 episodes, 636 seasons
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 4.4.3-47 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
configuration: --target-os=linux --cross-prefix=/home/spksrc/tvh-update/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/home/spksrc/tvh-update/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/home/spksrc/tvh-update/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/home/spksrc/tvh-update/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-avresample --disable-debug --disable-static --disable-doc --extra-version=47 --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libcodec2 --enable-libxml2 --enable-demuxer=dash --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libopenjpeg --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libcaca --enable-libdc1394 --enable-libvorbis --enable-libwebp --enable-libzmq --enable-gnutls --enable-libopus --enable-libsoxr --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librabbitmq --enable-libzvbi --enable-libx264 --enable-libx265 --enable-libvpx --enable-libshine --enable-chromaprint --enable-libdav1d --enable-frei0r --enable-librist --enable-libzimg --enable-libfdk-aac --enable-nonfree --enable-libass --enable-libaom --enable-libsvtav1 --enable-libsvthevc --arch=x86_64 --enable-vaapi --enable-libmfx --enable-libdrm
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by ConfusedPolarBear** [comment]
> For some reason icant make it start and detext intros

Can you elaborate on this? What happens when you run the Detect Introductions task?

> and the skip does not appear when playing the show.

In the current version of the plugin, the skip button only appears when you are using the modified web interface and when the Detect Introductions task has successfully ran at least once.

In regards to the other issue you opened (#141), the steps to install ffmpeg depend on how you installed Jellyfin.

1. How did you install Jellyfin? Did you use:
    * A Docker image? Which one?
    * A SynoCommunity package?
    * Something else?

2. Can you post a copy of Jellyfin's log file after you run the Detect Introductions task (be sure to copy the log's contents after the line that says `Executing Detect Introductions`)?

**Comment by ConfusedPolarBear** [comment]
Closing as no additional information has been provided.
