### ISSUE TITLE
How to install ffmpg?

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [ConfusedPolarBear/intro-skipper#141]
### Describe the bug

It says to install it but i can't find a way of installing it.

### Operating system

Synology NAS DSM

### Jellyfin installation method

DSM

### Support Bundle

Same as before

**Comment by ThijmenDam** [comment]
I struggled with this for a while, but eventually found an `INSTALL.md` file in the repository. I followed the instructions in that file.

**Comment by ConfusedPolarBear** [comment]
Closing in favor of #140
