### ISSUE TITLE
Autoskip intro on androidTV client

### ISSUE THREAD

**Issue by Fallenbagel** [ConfusedPolarBear/intro-skipper#15]
Auto Skipping works great on all clients except android TV. On android tv stable, it doesn't skip it just plays ignoring the plugin. On android tv debug, it tries to skip and crashes. 
I tried to check logs to debug what was happening but there's nothing in server logs so I was wondering if there was a way to check.

**Comment by sambartik** [comment]
Have you tried checking android tv client logs via ADB?

**Comment by Fallenbagel** [comment]
> Have you tried checking android tv client logs via ADB?

Oh. I'm not exactly sure how to do that, bc in the case of my phone I use a data cable. It can connect over network?

On a related note, I have been trying to build a skip-intro button directly into androidTV meanwhile.

**Comment by sambartik** [comment]
Yeah, sure you can! I am not very experienced in the android ecosystem, but I was able to connect to my android TV via ADB. I just needed to enable something in the developer settings and find the IP address of my TV. Then I connected to it on my laptop: `adb connect [IP]`.

**Comment by Fallenbagel** [comment]
> Yeah, sure you can! I am not very experienced in the android ecosystem, but I was able to connect to my android TV via ADB. I just needed to enable something in the developer settings and find the IP address of my TV. Then I connected to it on my laptop: `adb connect [IP]`.

THANKS ill give it a try tonight

**Comment by mueslimak3r** [comment]
The trick to getting it working wirelessly is to, after you've connected the device via USB and confirmed adb is working wired, type `adb tcpip 5555` to set the port for both devices to use for wireless adb. After that you should be able to unplug your device and use `adb connect ip:5555`

**Comment by mueslimak3r** [comment]
Once I get the plugin running on my 10.8 stable server I can troubleshoot and try to fix the crash/issues with the Android tv app

**Comment by Fallenbagel** [comment]
> The trick to getting it working wirelessly is to, after you've connected the device via USB and confirmed adb is working wired, type `adb tcpip 5555` to set the port for both devices to use for wireless adb. After that you should be able to unplug your device and use `adb connect ip:5555`

Gonna try this in a while. Hopefully I can get to the bottom of it

> Once I get the plugin running on my 10.8 stable server I can troubleshoot and try to fix the crash/issues with the Android tv app

That'd be great! I'll try to see if I can debug too

**Comment by Yankees4life** [comment]
Yeah...autoskip is working in my end (Tivo Stream 4K running the latest beta version of jellyfin and running the latest version of jellyfin on my win10 laptop). Hopefully, you figure out what's going on in your end.

**Comment by Fallenbagel** [comment]
> Yeah...autoskip is working in my end (Tivo Stream 4K running the latest beta version of jellyfin and running the latest version of jellyfin on my win10 laptop). Hopefully, you figure out what's going on in your end.

Is it on exoplayer or does it also work w libvlc?

**Comment by mueslimak3r** [comment]
> Is it on exoplayer or does it also work w libvlc?

Which of these do and don't work for you?

> Maybe I should try the latest beta version

The latest stable (0.13.6) is the same as the beta. However, some users have reported that switching between fixed issues for them, but that's likely just cache being cleared or something. You can clear the cache in the android tv settings.

**Comment by Fallenbagel** [comment]
> Which of these do and don't work for you?

None on official release it just ignores the setting and keeps playing. Both crashes on debug.

> The latest stable (0.13.6) is the same as the beta. However, some users have reported that switching between fixed issues for them, but that's likely just cache being cleared or something. You can clear the cache in the android tv settings.

Yeah im going to try this tonight. Clear cache or re-install and see if it helps. If not, then I'll just try to implement the skip-intro button. Shouldn't be too hard (maybe)

**Comment by Fallenbagel** [comment]
> The latest stable (0.13.6) is the same as the beta. 

I was running debug manually compiled as I wanted to test out some new functions such as subtitle delay and stuff. 

Anyways, I just got it working on official stable, I have no idea what did it but I'm guessing clearing of cache. But still, I am going to work on the manual skip intro button for android tv as automatic skipping is not that efficient in some shows where sometimes there are intros that I do want to watch and stuff that are part of the main story.

**Comment by mueslimak3r** [comment]
I can reproduce this issue on android TV:

json from the auto skip message:

org.jellyfin.androidtv.debug I/OkHttpWebsocketSession: Receiving (raw) message {"MessageType":"GeneralCommand","MessageId":"4269f321ae1442609b53fb416a1c1676","Data":{"Name":"DisplayMessage","ControllingUserId":"00000000000000000000000000000000","Arguments":{"Header":null,"Text":"Automatically skipped intro","TimeoutMs":"2000"}}}

Crash from `"Header":null`:

```
org.jellyfin.androidtv.debug E/ACRA: ACRA caught a JsonDecodingException for org.jellyfin.androidtv.debug
    kotlinx.serialization.json.internal.JsonDecodingException: Unexpected 'null' when string was expected
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.asLiteral(TreeJsonDecoder.kt:161)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:151)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:35)
        at kotlinx.serialization.internal.TaggedDecoder.decodeString(Tagged.kt:231)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:142)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:138)
 ```
 
 @ConfusedPolarBear perhaps `"Header":null` could just be replaced with `"Header":""`?

There is also another messages endpoint that could be used, and it doesn't require a header (/Sessions/SESSIONID/Message).

**Comment by ConfusedPolarBear** [comment]
> perhaps `"Header":null` could just be replaced with `"Header":""`

Added in 1ca7a9ec.

**Comment by sourpatched** [comment]
After upgrading to 10.8.1 Auto skip working on ATV without plugin or ATV app updated.
