### ISSUE TITLE
Won't analyze episodes 

### ISSUE THREAD

**Issue by Cyberman1234** [ConfusedPolarBear/intro-skipper#20]
Hi,

I've just installed ver 0.1.0.0 of intro-skipper and am on Jellyfin 10.8.0. When i try to analyze episodes through the scheduled tasks it fails and says completed in 0 minutes and 0 seconds in the logs. I have tried installing version 0.0.3.0 and 0.0.2.0 and both of these do the same thing.

**Comment by Fallenbagel** [comment]
Did you install fpalc in your image?
