### ISSUE TITLE
Option to export/save as .edl file for other players to skip found intros [Feature] 

### ISSUE THREAD

**Issue by cooljimy84** [ConfusedPolarBear/intro-skipper#21]
**Describe the feature you'd like added**
The option to export all found intros (or save as you find) to a .edl file and save along side the video file to allow other player to skip intros.
Kodi for example is planing on adding option 4 and 5 for intro and outro.
[https://kodi.wiki/view/Edit_decision_list]

**Additional context**
Not sure a huge amount of people use Jellyfin and separate Kodi, but could help those with external players.

**Comment by ConfusedPolarBear** [comment]
Initial support for this has been added to the `edl` branch.

**Comment by cooljimy84** [comment]
I've managed to build and get the edl branch running on my server. It's created edl files that work with Kodi. Hats off to you for this !

**Comment by damomato** [comment]
> I've managed to build and get the edl branch running on my server. It's created edl files that work with Kodi. Hats off to you for this !

Hi, how did you use this with Kodi? I found the TV Skip Intro add-on in the following repo, did you use that?
https://github.com/aenemapy/aenemapyrepo

Thanks

**Comment by damomato** [comment]
My earlier comment was a bit premature. I can't seem to generate the .edl files. How do I add the repo to Jellyfin? I've tried the following but in the plugin I can't see the options as described in the wiki

https://raw.githubusercontent.com/ConfusedPolarBear/intro-skipper/edl/manifest.json

**Comment by cooljimy84** [comment]
> > I've managed to build and get the edl branch running on my server. It's created edl files that work with Kodi. Hats off to you for this !
> 
> Hi, how did you use this with Kodi? I found the TV Skip Intro add-on in the following repo, did you use that? https://github.com/aenemapy/aenemapyrepo
> 
> Thanks

I also found that, but it didn't seem to work on kodi 19 and above, due to the change to python 3. I just used the built in feature of commercial skipping.

**Comment by ConfusedPolarBear** [comment]
Support for saving intro timestamps to EDL files has been merged into the master branch and will be available with the next plugin release (v0.1.6).
