### ISSUE TITLE
[Bug] Episodes are not ordered correctly within season

### ISSUE THREAD

**Issue by Flo56958** [ConfusedPolarBear/intro-skipper#25]
**Describe the bug**
The episodes to be analyzed are ordered by the sorting title instead of the episode number (index number).

As seen by this code segment:

https://github.com/ConfusedPolarBear/intro-skipper/blob/f6abe81876b68913fd91799cbad7502beabb1555/ConfusedPolarBear.Plugin.IntroSkipper/Entrypoint.cs#L111

This leads to bad intro detection in certain seasons. For example, one season I've tested has 64 episodes and changes the intro every 12-15 episodes. As the episodes are scrambled by sorting after the sorting title and not chronological, the plugin compares wrong intro sequences and finds no timestamps (tested on small subset of 5 episodes). After testing I have found that changing `"SortName"` to `"IndexNumber"` in the mentioned line solves the wrong sorting and results in 100% intro detection within the tested episodes. It would also fix the Fingerprint Visualization interface as it uses the same sorting from the same list.

Is there a reason for sorting with the title instead of chronological?

**System information**
- Plugin version: latest master commit [f6abe81](https://github.com/ConfusedPolarBear/intro-skipper/commit/f6abe81876b68913fd91799cbad7502beabb1555)
- Jellyfin version: 10.8.0
- Jellyfin installation method: Native (Service)
- OS: Windows 11

**Comment by ConfusedPolarBear** [comment]
Thank you for the very detailed bug report & root cause analysis. I just tested this change locally and didn't see any negative side effects, so I'll go ahead and change the plugin to use the new sort order.

> Is there a reason for sorting with the title instead of chronological?

None of the code that I had seen previously had sorted by that field.
