### ISSUE TITLE
[Bug] Progress Reset

### ISSUE THREAD

**Issue by LubricantJam** [ConfusedPolarBear/intro-skipper#30]
**Describe the bug**
I have a large library and my scan over the course of the week got to around 38%. After this latest update, it's now gone back to 0%. Is this normal for this update?

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: Docker
- OS: Ubuntu

**Comment by sourpatched** [comment]
What hardware do you have?
I don't use docker and found the plugin to take a few hours.

**Comment by ConfusedPolarBear** [comment]
v0.1.5 doesn't correctly calculate the percentage that's displayed in the scheduled task UI in some situations - this should be resolved with b645ea85 .

**Comment by sfkpmr** [comment]
Somewhat related, can you tell what has been scanned? 

The installation instructions say "After a season has completed analyzing, play some episodes from it and observe the results", but all I find in the logs are failed seasons "Failed to find an introduction".

**Comment by LubricantJam** [comment]
Might need a separate issue for this or try the beta on-going to see if that helps. I'm closing this though as this issue is now resolved.
