### ISSUE TITLE
Doesn't work on Android TV

### ISSUE THREAD

**Issue by sourpatched** [ConfusedPolarBear/intro-skipper#31]
**Describe the bug**
I have auto skip on since I don't have docker and didn't want to upload a modded GUI. Web GUI works and Android Phone app but ATV does not auto skip.

**System information**
- Plugin version: 1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: DEB File
- OS: Android TV

**Jellyfin logs**
N/A
paste logs here
```

**Comment by ConfusedPolarBear** [comment]
Likely a duplicate of #15.

**Comment by sourpatched** [comment]
I believe so.
