### ISSUE TITLE
[Doc] No web interface in release's zip file

### ISSUE THREAD

**Issue by Extarys** [ConfusedPolarBear/intro-skipper#33]
The [current documentation](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/web_interface.md) to install the web interface says:
> Download the latest compiled version of the web interface from [the releases tab](https://github.com/ConfusedPolarBear/intro-skipper/releases) (or compile [from source](https://github.com/ConfusedPolarBear/jellyfin-web/tree/intros))

But the release zip only contains the DLL of the plugin. I'm unsure if one way to install would be to clone the **intros** branch from your **jellyfin-web** repo and simply mount it in Jellyfin docker container or if there are other steps involved.

Or I might have simply missed something here?

Can't wait to try the plugin, thank you! Hope Jellyfin eventually allow plugins to modify the web UI without having to go through such extremes.

**Comment by Catsrules** [comment]
Yeah I got a little confused as well but there is link In the description of the release file, last line 

> The modified web interface with the intro skip button can be downloaded from [here](https://github.com/ConfusedPolarBear/intro-skipper/suites/6972367812/artifacts/272458772).

Note you need to be logged in to GitHub for the download to work.

**Comment by Extarys** [comment]
Ohh thanks for that! No idea where I would have find that hahaha
Really appreciate you stepped in, I thought I was going crazy.


I'll leave this issue open as the doc still needs to be updated.
