### ISSUE TITLE
[Bug] [ERR] The installed version of ffmpeg does not support chromaprint

### ISSUE THREAD

**Issue by Krupski19** [ConfusedPolarBear/intro-skipper#36]
**Describe the bug**
Trying to run the Analyze Episodes Scheduled Task fails instantly when triggered.  Checking Jellyfin logs shows that the plugin failed to find a version of ffmpeg that supports chromaprint.  Current ffmpeg in use is the latest ffmpeg 5.0.1 from Jellyfin.  Tried to switch to system installed ffmpeg, version 4.2.7-0ubuntu0.1, and received the same result.

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: Native
- OS:  Ubuntu 20.04.4

**Jellyfin logs**
[jellyfin20220622.log](https://github.com/ConfusedPolarBear/intro-skipper/files/8959503/jellyfin20220622.log)
```
Thank you for the help and thanks for the awesome plugin!

**Comment by Shadowghost** [comment]
You need at least `jellfin-ffmpeg 5.0.1-5`. You can install it by installing the `jellyfin-ffmpeg5` package if you're using the Jellyfin Debian APT repository.
