### ISSUE TITLE
[Feature] Library selection

### ISSUE THREAD

**Issue by bruor** [ConfusedPolarBear/intro-skipper#37]
I'd like to see the ability to limit which libraries the plugin will scan for intro skipping. 

I have one TV library for episodes where the media files are hosted locally,  and another one that is 7000+ .strm files (which just contain a link to a file on a web server somewhere).  In the comparison section of the plugin configuration screen it shows all of the TV series in my .strm library, but I'm unsure how the plugin will handle those files and I'd hate to see it trying to stream all that remote media to try to analyze it.

**Comment by ConfusedPolarBear** [comment]
Support for this has been added in add5a46576ec108908a7d319a57016550a48673f.
