### ISSUE TITLE
[Feature] Make intro time requirements configurable by the user

### ISSUE THREAD

**Issue by gruenfink** [ConfusedPolarBear/intro-skipper#38]
> Show introductions will only be detected if they are:
> Located within the first 25% of an episode, or the first 10 minutes, whichever is smaller

There are quite a few episodes in my library where the intro starts after the 10 minute mark. The plugin fails to detect these intros with its current hardcoded analyze duration limit of 600 seconds. It would be very much appreciated if you allowed the user to change this setting in a config file or the GUI.

Personally, I'd probably set it to 40% or 20 minutes, whichever is smaller. These values should cover nearly 100% of episodes instead of the current ~95%. The increased resource usage would be fine, since the audio-based scan is very quick and the fingerprint data require minimal disk space.

Offering just two scan options in the GUI would also provide a pretty nice user experience:

* **Quick scan (default)** detects most intros (25%/10m)
* **Full scan** takes twice as long and detects virtually all intros (40%/20m)

**Comment by conkydong** [comment]
Recently I watched the new episodes of „Evil (2019)“. Sometimes the intro even starts at 20:30 or later.

**Comment by ConfusedPolarBear** [comment]
This is being worked on in the `custom-analysis` branch.

**Comment by ConfusedPolarBear** [comment]
This feature has been merged into the main branch and will be released as part of v0.1.6 ([beta version](https://github.com/ConfusedPolarBear/intro-skipper/releases/tag/v0.1.6-beta2)).
