### ISSUE TITLE
[Bug] Spaces in tv episode names cause issues

### ISSUE THREAD

**Issue by okan35** [ConfusedPolarBear/intro-skipper#42]
**Describe the bug**
It seems having spaces in tv episode name is causing fingerprint issues because when I removed them before I didn't have issues.

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: Windows installer exe
- OS: Windows 10

**Jellyfin logs**
```
pastebin.com/kiwk8ajR
```

**Comment by ConfusedPolarBear** [comment]
This should be fixed by cf1dc66970dac52830d7ad5c84db462b8f6ab64a.

**Comment by okan35** [comment]
Thanks, I will test it when there is a new release.

**Comment by ConfusedPolarBear** [comment]
Are you still experiencing this issue with v0.1.6?

**Comment by okan35** [comment]
Unfortunately I haven't been able to try it and won't be able to try for the next some weeks. But if you just name your files as "S01E05 - Some Funny Episode Name" and your show names as "Some Tv Show (2017)"

It should give you errors in logs if it is not fixed.

**Comment by ConfusedPolarBear** [comment]
Closing as v0.1.6 (and v0.1.7) have been released and confirmed to work on Windows 10.
