### ISSUE TITLE
[Bug] Can't press skip intro button on Android

### ISSUE THREAD

**Issue by kimpig** [ConfusedPolarBear/intro-skipper#43]
**Describe the bug**

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: native 
- OS: Windows 10

I checked that the PC is working normally.
But on the Android app, the button pops up, but I can't press it. Is there any solution?

**Comment by Sabiancym** [comment]
Skipping isn't working at all for me on Android using the official Jellyfin Client.  I checked the same episodes on PC and automatic skipping works fine, but I have yet to see a single intro skipped while using my Android phone.

**Comment by ConfusedPolarBear** [comment]
> But on the Android app, the button pops up, but I can't press it. Is there any solution?

Does [this version](https://github.com/ConfusedPolarBear/intro-skipper/suites/7266924623/artifacts/292329010) of the web interface resolve the issue?

**Comment by kimpig** [comment]
> > But on the Android app, the button pops up, but I can't press it. Is there any solution?
> 
> Does [this version](https://github.com/ConfusedPolarBear/intro-skipper/suites/7266924623/artifacts/292329010) of the web interface resolve the issue?

Yes, I can also press the button on Android in this version.
However, if I press it on Android, the problem I mentioned, #44, does not occur, while #44 still occurs on PCs.

**Comment by kimpig** [comment]
This issue is resolved in the latest version.
Closing the issue.
