### ISSUE TITLE
[Feature] Skip and play automatically

### ISSUE THREAD

**Issue by kimpig** [ConfusedPolarBear/intro-skipper#44]
**Describe the feature you'd like added**

Skipping is normal, but automatically pauses after skipping.
I hope it plays right away without pausing.

**Additional context**

**Comment by gruenfink** [comment]
Confirming this bug. A click on the button does skip the video to the correct timestamp but also pauses the video.

My initial suspicion was that the mouse click might be registered twice, as a button press and also as a click on the background video, i.e. a pause action. But if the button is clicked while already in a paused state, the video still doesn't play on its own. So it's not that.

**Comment by kimpig** [comment]
> I merged the changes from the forked web version into my own copy that had a couple other modifications, and had this issue. Effectively reverting [this](https://github.com/ConfusedPolarBear/jellyfin-web/commit/5ad964131b15230accd94018f072929c864a379d) commit fixed my issue...

I reverted [that](https://github.com/ConfusedPolarBear/jellyfin-web/commit/5ad964131b15230accd94018f072929c864a379d) commit and confirmed that there was no problem. I'll fix the tag with a bug.

**Comment by kimpig** [comment]
> I merged the changes from the forked web version into my own copy that had a couple other modifications, and had this issue. Effectively reverting [this](https://github.com/ConfusedPolarBear/jellyfin-web/commit/5ad964131b15230accd94018f072929c864a379d) commit fixed my issue...

I found a problem.
PlayPause works fine on PC, but it pauses when I press the button on Android.

unpause works fine on Android, but it pauses when I press the button on PC.

Is there a solution?

**Comment by ConfusedPolarBear** [comment]
Container image `ghcr.io/confusedpolarbear/jellyfin-intro-skipper:28502dbd5e` (built from [28502db](https://github.com/ConfusedPolarBear/jellyfin-web/commit/28502dbd5ea7e007aaacd1a4eaf0739264f382a4)) resolves this issue for me (tested on Firefox running on Linux and Windows).

**Comment by kimpig** [comment]
> Container image `ghcr.io/confusedpolarbear/jellyfin-intro-skipper:28502dbd5e` (built from [28502db](https://github.com/ConfusedPolarBear/jellyfin-web/commit/28502dbd5ea7e007aaacd1a4eaf0739264f382a4)) resolves this issue for me (tested on Firefox running on Linux and Windows).

It works perfectly with Mobile and PC.
Closing the issue.

**Comment by CTalvio** [comment]
Running JF native.

Skipping is still pausing the playback for me.

I downloaded the modified web client and simply pointed the my JF server to a new location for JF web with a systemd drop in.

Apparently this does not get me a version that works?

**Comment by kimpig** [comment]
> CTalvio

Maybe you should build with the modified code.

**Comment by sambartik** [comment]
Exactly as kimpig says. Currently you need to build it yourself to have the latest patched frontend. The GH actions link provided in the native doc page is outdated judging by the downloaded file hash suffix [4f8a2c2a96](https://github.com/ConfusedPolarBear/jellyfin-web/commit/4f8a2c2a967745ae30024cac693d69cd0146d1c4), which is the hash of a commit that comes before the mentioned [28502db](https://github.com/ConfusedPolarBear/jellyfin-web/commit/28502dbd5ea7e007aaacd1a4eaf0739264f382a4) commit.

**Comment by ConfusedPolarBear** [comment]
I've updated the native documentation page with instructions on how to download the latest version of the web interface.
