### ISSUE TITLE
[Bug] Can't press skip button on iOS

### ISSUE THREAD

**Issue by avion540** [ConfusedPolarBear/intro-skipper#50]
**Describe the bug**
Skip button is hidden behind the rest of the web UI on my iPhone X, see image below. I do not have a larger iPhone to try it on.   
[iOS screenshot](https://pixelfed.social/storage/m/_v2/189162097295364096/2f76a232a-f08599/EjUarGaYdQV9/S26NgdcoRuEeKQeGRI5V3Z7dvuVAjI3D5mq9ZXdr.png)

**System information**
- Plugin version: 0.1.5.0
- Jellyfin client: Official iOS Jellyfin app v1.5.0 (Native Video Player turned off)
- Client OS: iOS 15.5
- Jellyfin server version: 10.8
- Jellyfin server installation method: ConfusedPolarBear docker image
- Server OS: Debian 11

**Jellyfin logs**
```
No relevant logs found
```

**Comment by ConfusedPolarBear** [comment]
Does [this version](https://github.com/ConfusedPolarBear/intro-skipper/pkgs/container/jellyfin-intro-skipper/27901338?tag=83fc2cf4fe) of the container resolve the issue?

**Comment by avion540** [comment]
Yes, that version works perfectly! The button isn't obscured and I can use it by pressing it twice.
