### ISSUE TITLE
[Bug] Automatic skip before v0.1.6 doesn't work with Android TV

### ISSUE THREAD

**Issue by sourpatched** [ConfusedPolarBear/intro-skipper#57]
Android TV 0.14 beta https://github.com/jellyfin/jellyfin-androidtv/issues/1853

**Comment by Yankees4life** [comment]
Latest release of this plugin is working with the latest Android TV beta version on my Tivostream. 

Might need to clear cache sometimes to get it working tho but it works

**Comment by sourpatched** [comment]
Tested and has worked, no longer crashes.
