### ISSUE TITLE
Infuse support

### ISSUE THREAD

**Issue by nmcc1212** [ConfusedPolarBear/intro-skipper#62]
Is there a way to make this plugin work when using the infuse player?

**Comment by jenslys** [comment]
There is a post on the offical Infuse community forum requesting this:
https://community.firecore.com/t/support-skip-intro-for-jellyfin-via-plugin/37841

**Comment by ConfusedPolarBear** [comment]
If the automatic skip feature doesn't work with Infuse, the only way to make the plugin work with Infuse is to wait for them to add native support for a skip intro button that uses the plugin's [HTTP API](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/api.md).

**Comment by amddeus** [comment]
Does it automatic skip work with Infuse? I can't seem to get it to work

**Comment by nmcc1212** [comment]
please read what was said above…
and check the link posted by jenslys

**Comment by amddeus** [comment]
> please read what was said above…
> and check the link posted by jenslys

Well you closed the issue so I thought it would work… Also it clearly says “if” the automatic skip doesn’t work which implies that it may work

**Comment by nmcc1212** [comment]
i closed it as this cannot be done without the Infuse devs first adding support, as was said above…
