### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tywentghxst** [ConfusedPolarBear/intro-skipper#63]
Does this work with a windows install? I'm using windows version no docker, I read the install and followed multiple times and doesn't seem to work for me, so I'm not sure if i read it wrong and it doesn't work how I think?

**Comment by ElStefanos** [comment]
Same I installed modified jellyfin-web. Automatic skip works but no button. Cant even find it in inspect element.

**Comment by tywentghxst** [comment]
Exactly the same! Auto Skip works but no button

**Comment by ElStefanos** [comment]
Maybe its because of the custom CSS but I don't see any changes in developer options.
I'll try removing it.

**Comment by tywentghxst** [comment]
I actually thought of that too, but haven't tried it since I'm away from my PC, please let me know how it goes!

**Comment by ElStefanos** [comment]
No It doesn't everything leads me that I probably Installed Main Branch of jellyfin-web since they have same read me. But there is no way for that I checked. I will try again and I will let you know if that was the problem.

**Comment by tywentghxst** [comment]
Dang, I know I installed the modified branch for sure lol check 3 times to make sure

**Comment by ElStefanos** [comment]
Well I'm building again wish me luck lol. Will let you know if that was the problem.

**Comment by ElStefanos** [comment]
Well it just broke player footer It doesn't disappear.

**Comment by tywentghxst** [comment]
Dang, and the button still ain't popping up?

**Comment by ElStefanos** [comment]
No.  We shall wait for the creator himself the almighty ConfusedPolarBear

**Comment by ConfusedPolarBear** [comment]
I spun up a Windows 10 VM to test this and was able to get the modified web interface working with the following steps:

1. Download the pre-compiled web interface from [GitHub actions](https://github.com/ConfusedPolarBear/intro-skipper/suites/7555975919/artifacts/312015938)
    2. Note that GitHub actions download links will only work if you are signed in to GitHub
2. Extract the `dist` folder to a convient location
2. Make a backup of the original web interface (located in `C:\Program Files\Jellyfin\Server\jellyfin-web`)
4. Copy all files inside the `dist` folder to `C:\Program Files\Jellyfin\Server\jellyfin-web`
5. Refresh the main Jellyfin page with cache disabled

**Comment by tywentghxst** [comment]
IT WORKED!!! THANK YOU and thank you for you amazing work!

**Comment by tywentghxst** [comment]
@ConfusedPolarBear i do have a question, when i press skip intro it pauses the video after the skip, is there a way to stop it from pausing?

**Comment by ConfusedPolarBear** [comment]
> when i press skip intro it pauses the video after the skip, is there a way to stop it from pausing?

Not currently - the unpausing bug is tracked in #44

**Comment by tywentghxst** [comment]
Ok thanks again!

**Comment by ElStefanos** [comment]
Yeah still doesn't work for me. Maybe it's because of the show. Anyway I'm legally obtaining few more will let you know if it works in an hour or two.

**Comment by tywentghxst** [comment]
Did you use the plugging to analyze the episodes?

**Comment by ElStefanos** [comment]
Well it was because of the show others work fine. thanks for the help.

**Comment by ElStefanos** [comment]
Works now it was problem in the show.
