### ISSUE TITLE
Bug: Analyze episodes Completed after 0 minute(s) and 0 seconds

### ISSUE THREAD

**Issue by avion540** [ConfusedPolarBear/intro-skipper#7]
Installed 0.0.0.2 using the plugin manifest and your docker container attached to a Jellyfin 10.8 beta 3 library. 
Restarted the server and manually started the Scheduled Task but it silently failed and logs `Analyze episodes Completed after 0 minute(s) and 0 seconds` on the first scan.

**Comment by ConfusedPolarBear** [comment]
Does version 0.0.0.3 work?

**Comment by avion540** [comment]
It does! Scan successfully started.
