### ISSUE TITLE
[Bug] Skip intro button not shown on Android TV and not touchable on Android

### ISSUE THREAD

**Issue by JVT038** [ConfusedPolarBear/intro-skipper#77]
So I have 2 issues:

1: On my Android phone, the skip intro button can't be touched / triggered. It is shown, but when I touch it, the playback controls show up, instead of skipping the intro. Jellyfin version 2.4.4 on Android 11

2: On my Android TV, the skip button doesn't show up, so I can't even skip it. I would rather not have auto skip, as I sometimes watch the intro and sometimes not. So I want to keep that choice. Jellyfin version 0.14.1

**System information**
- Plugin version: 0.16.0
- Jellyfin server version: 10.8.4
- Jellyfin installation method: Docker, official Jellyfin image
- OS: Android

**Comment by ConfusedPolarBear** [comment]
> 1: On my Android phone, the skip intro button can't be touched / triggered.

* What model of phone do you have?
* What version of the modified web interface did you install?

> 2: On my Android TV, the skip button doesn't show up, so I can't even skip it.

The Android TV client [does not currently](https://github.com/jellyfin/jellyfin-androidtv/issues/1800) support the skip intro button.

**Comment by JVT038** [comment]
So I checked which modified web interface I had, and it turns out I have an outdated one ([this one from 2 months ago](https://github.com/ConfusedPolarBear/intro-skipper/actions/runs/2513020837)), which was the cause of the issues on my phone.
I updated the interface, and it was fixed instantly.
Also, I recommend you update the link in your [web interface file](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/web_interface.md#method-1-mounting-the-new-web-interface), because the current link is outdated (the same one I had from 2 months ago)
