### ISSUE TITLE
Option to not skip create a skip for E1 ? [Feature] 

### ISSUE THREAD

**Issue by cooljimy84** [ConfusedPolarBear/intro-skipper#78]
**Describe the feature you'd like added**
Sometimes it nice to see the intro, like on E1 of Season X, option to not compute E01

**Additional context**
Only cause i've got once show that I wanted to watch the intro for.

**Comment by antoinedelia** [comment]
Thanks for implementing this!

I stumbled upon a case where a show does not have any intro for its first episode. So the "true" first episode is the second one (the show in question is Severance).

Could be great to add a way to not skip the intro for the first episode that contains an intro!
