### ISSUE TITLE
Version: 10.8.4 doesn't work?[Bug] 

### ISSUE THREAD

**Issue by tywentghxst** [ConfusedPolarBear/intro-skipper#80]
doesnt seem to work on 10.8.4, has it been updated for this version or could me install be broken???

**System information**
- Plugin version: Intro Skipper 0.1.6.0
- Jellyfin version: Version: 10.8.4
- OS: windows

**Comment by Pfuenzle** [comment]
For me it's working fine, it still says I'm connecting from Jellyfin-Web 10.8.1, but functionally it is working as intended.

**Comment by tywentghxst** [comment]
> For me it's working fine, it still says I'm connecting from Jellyfin-Web 10.8.1, but functionally it is working as intended.

so after uninstalling and reinstalling the plugin a few times auto skip works now, but the skip button doesn't, does it work for you?

im gonna reinstall the skip button to my server now and see if that fixes it

**Comment by tywentghxst** [comment]
its working now, just had to do a few reinstalls, several times for some reason it just started now, thanks
