### ISSUE TITLE
[Feature] A lot of shows have blank audio where the intro ends could it be used to find intro

### ISSUE THREAD

**Issue by Dnkhatri** [ConfusedPolarBear/intro-skipper#81]
I was previously using a mpv lua plugin that forwarded the show to the next blank audio on pressing tab which most of the time was the start of the episode so was able to skip intro. As this was enough for 90% of the shows to skip intro I was wondering if similar can be used to improve intro detection as well as give this option of moving to the first or 2nd blank place where using the skip intro button where the algos were not able to find the intro.

something like this

https://github.com/detuur/mpv-scripts/blob/master/skiptosilence.lua

**Comment by ConfusedPolarBear** [comment]
Thanks for the suggestion & link to the example program. I tested the silence detection filter and was able to improve the accuracy of detected introductions. I've integrated the filter into the plugin; the changes are currently in the `algorithm_rewrite` branch, but will be merged into master before the next plugin release.

**Comment by Dnkhatri** [comment]
Hi any way I could get the plugin to try?

**Comment by ConfusedPolarBear** [comment]
https://github.com/ConfusedPolarBear/intro-skipper/suites/8186922641/artifacts/356141145. This version of the plugin is still under heavy development so make sure to backup your server before running it.

**Comment by Dnkhatri** [comment]
The accuracy as well as the number of intros found seem to have gone up. I will close this as I consider it done.
