### ISSUE TITLE
[Feature] user defined pre-roll for skips

### ISSUE THREAD

**Issue by mueslimak3r** [ConfusedPolarBear/intro-skipper#83]
* an adjustable setting for skipping to to the end of the intro minus some number of seconds/ms.

This would be useful when the end of the intro often slightly overlaps with content I want to watch. I often want to see the last second of the intro just be be sure that I didn't miss an important piece of dialogue at the beginning of the scene following an intro.

Additionally, there are some shows such as American horror story which, following the intro, show a black screen with the location and date of the events of the episode. A sound effect plays when that screen is shown and it likely is picked up when fingerprinting since it's the same for each episode.

**Comment by ConfusedPolarBear** [comment]
Support for this was added in commit bbed34b and will be available in the next release of the plugin.
