### ISSUE TITLE
[Bug] Not queuing episode *insert id* as no path was provided by Jellyfin

### ISSUE THREAD

**Issue by JVT038** [ConfusedPolarBear/intro-skipper#87]
**Describe the bug**
When I run the task, it shows around 900 lines of this error, with a different episode:
`Not queuing episode <episode id> as no path was provided by Jellyfin`

I know there is another issue with the same bug, but it was closed without any solution being provided, so I'm opening a new issue.

**System information**
- Plugin version: 1.0.6
- Jellyfin version: 10.8.4
- Jellyfin installation method: Docker, official jellyfin/jellyfin image
- OS: Synology DSM 7

**Comment by ConfusedPolarBear** [comment]
1. Do you have the TVDB plugin installed?
2. Do you have Jellyfin configured to fetch or display missing episodes?

**Comment by JVT038** [comment]
Yes to both

**Comment by ConfusedPolarBear** [comment]
See https://github.com/ConfusedPolarBear/intro-skipper/issues/84#issuecomment-1257125827

**Comment by ConfusedPolarBear** [comment]
Are you still experiencing this issue with v0.1.7?

**Comment by JVT038** [comment]
I think v0.1.7 fixed the issue.

Thank you for your work!
