### ISSUE TITLE
[Feature] Using black frame to detect intro or outro mpv lua

### ISSUE THREAD

**Issue by Dnkhatri** [ConfusedPolarBear/intro-skipper#88]
I am here again with another mpv lua script that I came across it works similarly like the previous one but uses the complete black frame to detect intro. I know you are using audio to detect intros but just posting this if you think it can help improve intro detection. I hope you will add outro detection as well as that would the upnext dialog that shows up for the next episode.

https://gist.github.com/bossen/3cfe86a6cdd61452dbb96865128fb327

**Comment by ConfusedPolarBear** [comment]
Thanks for the suggestion - support for this was added in 2bd972f3 & will be released in the next version.
