### ISSUE TITLE
Update jellyfin-web to 10.8.5

### ISSUE THREAD

**Issue by JVT038** [ConfusedPolarBear/intro-skipper#89]
While I've updated my server to 10.8.5, my web interface is still on 10.8.1, because I'm using the modified web interface.
Could you update the web interface to 10.8.5, so it includes all the bug fixes from 10.8.1 to 10.8.5?

**Comment by ConfusedPolarBear** [comment]
Done - an updated container image has been pushed & new precompiled builds are available for download.
