### ISSUE TITLE
Autoskip intros

### ISSUE THREAD

**Issue by Yankees4life** [ConfusedPolarBear/intro-skipper#9]
I think there should be an option to autoskip intros. This would bypass the need to compile the web interface for the plugin to work

**Comment by mueslimak3r** [comment]
When auto skipping, could you also add a "Message" API call with something such as "Skipping Intro"? This will display a toast/popup in the player with the text. The pop-up generated by the message API call is non-interactive and disappears after a second or two.

**Comment by Fallenbagel** [comment]
Auto Skipping works great on all clients except android TV. On android tv stable, it doesn't skip it just plays ignoring the plugin. On android tv debug, it tries to skip and crashes
